module.exports = [
    'Piccolo',
    'Flute',
    'Alto Flute',
    'Bass Flute',
    'Oboe',
    'Cor Anglais (English Horn)',
    'Bassoon',
    'Contrabassoon',
    'Clarinet in Bb',
    'Bass Clarinet',
    'E-Flat Clarinet',
    'Alto Saxophone',
    'Tenor Saxophone',
    'Baritone Saxophone',
    'Soprano Saxophone',
    'Trumpet in Bb',
    'Cornet',
    'Flugelhorn',
    'French Horn',
    'Trombone',
    'Bass Trombone',
    'Euphonium',
    'Tuba',
    'Violin',
    'Viola',
    'Cello',
    'Double Bass',
    'Harp',
    'Guitar',
    'Electric Guitar',
    'Bass Guitar',
    'Ukulele',
    'Banjo',
    'Mandolin',
    'Piano',
    'Organ',
    'Harpsichord',
    'Accordion',
    'Celesta',
    'Synthesizer',
    'Timpani',
    'Snare Drum',
    'Bass Drum',
    'Tom-Toms',
    'Cymbals',
    'Triangle',
    'Tambourine',
    'Marimba',
    'Xylophone',
    'Vibraphone',
    'Glockenspiel',
    'Tubular Bells',
    'Djembe',
    'Congas',
    'Bongos',
    'Tabla',
    'Sitar',
    'Sarod',
    'Tanpura',
    'Bansuri',
    'Shakuhachi',
    'Koto',
    'Erhu',
    'Pipa',
    'Guqin',
    'Didgeridoo',
    'Ocarina',
    'Pan Flute',
    'Theremin',
    'Steel Drums',
    'Hang Drum'
  ];
  